version: '3'
services:
  api:
    tty: true
    command: start
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/opt/app/src
    ports:
      - 3001:3001
    environment:
      - SHELL=/bin/sh
      - SELF_URL=http://localhost:3001
